### ISSUE TITLE
TG_ENCOUNTERS

### ISSUE THREAD

**Issue by NoFoolLikeOne** [NoFoolLikeOne/EDMC-USS-Survey#14]
Getting errors if TG_ENCOUNTERS variables are not set

Traceback (most recent call last):
  File "plug.pyo", line 296, in notify_journal_entry
  File "C:\Users\uggi\AppData\Local\EDMarketConnector\plugins\EDMC-USS-Survey\load.py", line 967, in journal_entry
  File "C:\Users\uggi\AppData\Local\EDMarketConnector\plugins\EDMC-USS-Survey\load.py", line 975, in journal_entry_wrapper
  File "C:\Users\uggi\AppData\Local\EDMarketConnector\plugins\EDMC-USS-Survey\load.py", line 1061, in statistics
KeyError: 'TG_ENCOUNTER_WAKES'(edited)

**Comment by NoFoolLikeOne** [comment]
Fixed in 1.4.2
